mountains = [
    {
        "name": "Mont Comi",
        "lat": "48.46575",
        "lon": "-68.21036",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://www.ipcamlive.com/5a348b49b950e"
    },
    {
        "name": "Mont Sutton",
        "lat": "45.08195",
        "lon": "-72.54837",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://montsutton.com/en/the-mountain/ski-conditions/"
    },
]
