mountains = [
    {
        "name": "Mont Comi",
        "lat": "48.46575",
        "lon": "-68.21036",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Sutton",
        "lat": "45.08195",
        "lon": "-72.54837",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Lyall",
        "lat": "48.80412",
        "lon": "-66.08622",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Gosford",
        "lat": "45.30179",
        "lon": "-70.86683",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Hereford",
        "lat": "45.08229",
        "lon": "-71.60047",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Albert",
        "lat": "48.93293",
        "lon": "-66.17872",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Massif du Sud",
        "lat": "46.62235",
        "lon": "-70.48768",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Edouard",
        "lat": "48.15209",
        "lon": "-70.28355",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Massif de Charlevoix",
        "lat": "47.27839",
        "lon": "-70.61007",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Orford",
        "lat": "45.31228",
        "lon": "-72.24160",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Saint-Anne",
        "lat": "47.08696",
        "lon": "-70.93293",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Montagne Noire",
        "lat": "46.24366",
        "lon": "-74.29391",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont des Allemands",
        "lat": "49.17056",
        "lon": "-71.47667",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Jacob",
        "lat": "48.41679",
        "lon": "-71.26578",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Brillant",
        "lat": "46.91041",
        "lon": "-71.46024",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Saint-Mathieu",
        "lat": "46.59737",
        "lon": "-72.83955",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Alta",
        "lat": "46.03834",
        "lon": "-74.24119",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Gallix",
        "lat": "50.16871",
        "lon": "-66.71735",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Plante (Val-David-Val-Morin)",
        "lat": "46.02857",
        "lon": "-74.19882",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Les Sentiers du Moulin",
        "lat": "46.97585",
        "lon": "-71.25365",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Hog's Back",
        "lat": "48.85675",
        "lon": "-66.10941",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Veyrier (Monts Groulx)",
        "lat": "51.53338",
        "lon": "-68.08214",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Valin",
        "lat": "48.61678",
        "lon": "-70.79904",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Le Valinouët",
        "lat": "48.63892",
        "lon": "-70.89714",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Ski Bromont",
        "lat": "45.28877",
        "lon": "-72.63882",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Owl's Head",
        "lat": "45.06267",
        "lon": "-72.29796",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Mont Blanc",
        "lat": "46.10164",
        "lon": "-74.48507",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Mont Tremblant",
        "lat": "46.22896",
        "lon": "-74.55661",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Mont Shefford",
        "lat": "45.36228",
        "lon": "-72.61082",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name":
            "Mont Adstock",
        "lat": "46.03107",
        "lon": "-71.20695",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    }
]
